# Generated by Django 3.0.3 on 2020-03-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
